flowchart LR
    User([مستخدم - صاحب نبات])
    Admin([المدير - Admin])

    subgraph Plantify
        direction TB
        UC1(إنشاء حساب وتسجيل الدخول)
        UC2(إدارة النباتات - حديقتي)
        UC3(استقبال تذكيرات الري التلقائية)
        UC4(تشخيص أمراض النباتات بالذكاء الاصطناعي)
        UC5(شراء المنتجات من المتجر)
        UC6(نشر ومتابعة في مجتمع محبي النباتات)
        
        UC7(إدارة بيانات المستخدمين)
        UC8(إدارة النباتات والمنتجات)
        UC9(إدارة طلبات المتجر)
        UC10(مراجعة وإصدار الإحصائيات)
    end

    User --> UC1
    User --> UC2
    User --> UC3
    User --> UC4
    User --> UC5
    User --> UC6

    Admin --> UC7
    Admin --> UC8
    Admin --> UC9
    Admin --> UC10
